name: "IDsculpt-geometry"
tag: ???
exp_root_dir: "outputs"
seed: 0

data_type: "coarse2fine-datamodule"
data:
  image_path: ''
  max_steps: ${trainer.max_steps}
  height: 512
  width: 512
  default_elevation_deg: 5.0
  default_azimuth_deg: 0.0
  default_camera_distance: 3.8
  default_fovy_deg: 28.0
  requires_depth: ${cmaxgt0orcmaxgt0:${system.loss.lambda_depth},${system.loss.lambda_depth_rel}}
  requires_normal: ${cmaxgt0:${system.loss.lambda_normal}}
  use_mixed_camera_config: false
  use_random_camera: True
  random_camera:
    height: 512
    width: 512
    batch_size: 1
    eval_height: 1024
    eval_width: 1024
    eval_batch_size: 1
    elevation_range: [ -15, 45 ]
    azimuth_range: [ -180, 180 ]
    camera_distance_range: [ 3.5, 4.5 ]
    fovy_range: [ 25.0, 45.0 ] 
    progressive_until: 0
    camera_perturb: 0.0
    center_perturb: 0.0
    up_perturb: 0.0
    eval_elevation_deg: ${data.default_elevation_deg}
    eval_camera_distance: ${data.default_camera_distance}
    eval_fovy_deg: ${data.default_fovy_deg}
    batch_uniform_azimuth: false
    n_val_views: 40
    n_test_views: 40


system_type: "IDsculpt-geo-system"
system:
  stage: geometry
  use_mixed_camera_config: ${data.use_mixed_camera_config}
  geometry_convert_inherit_texture: true
  geometry_type: "tetrahedra-sdf-grid"
  geometry:
    stage: ${system.stage}
    radius: 2.0
    n_feature_dims: 0
    force_shape_init: true
    isosurface_resolution: 512
    isosurface_deformable_grid: true
    shape_init: ???
    shape_init_params: 0.9
    shape_init_mesh_up: +y
    shape_init_mesh_front: +z

  material_type: "no-material"
  material:
    n_output_dims: 0

  background_type: "solid-color-background"

  renderer_type: "nvdiff-rasterizer"
  renderer:
    context_type: cuda

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "../../../sd_model/models--xanderhuang--normal-adapted-sd1.5/snapshots/a44f486d748a4bd0b46fc90113b5612afc58e0c4"
    prompt: ???
    use_perp_neg: True

  
  guidance_type: "sd-controlnet-vsd-ip1-guidance"
  guidance:
    # pretrained_model_name_or_path: "models--xanderhuang--normal-adapted-sd1.5"
    # pretrained_model_name_or_path_lora: "models--xanderhuang--normal-adapted-sd1.5"
    # vae_model_path: "models--stabilityai--sd-vae-ft-mse"
    # ip_ckpt: "IP_Adapter/models/ip-adapter-faceid-portrait-v11_sd15.bin"
    # ddim_scheduler_name_or_path: "models--runwayml--stable-diffusion-v1-5"
    # control_type: "landmark"
    # insightface_root: "sd_model/insightface"

    pretrained_model_name_or_path: "../../../sd_model/models--xanderhuang--normal-adapted-sd1.5/snapshots/a44f486d748a4bd0b46fc90113b5612afc58e0c4"
    pretrained_model_name_or_path_lora: "../../../sd_model/models--xanderhuang--normal-adapted-sd1.5/snapshots/a44f486d748a4bd0b46fc90113b5612afc58e0c4"
    vae_model_path: "../../../sd_model/models--stabilityai--sd-vae-ft-mse/snapshots/31f26fdeee1355a5c34592e401dd41e45d25a493"
    ip_ckpt: "../../../IP_Adapter/models/ip-adapter-faceid-portrait-v11_sd15.bin"
    ddim_scheduler_name_or_path: "../../../sd_model/models--runwayml--stable-diffusion-v1-5/snapshots/1d0c4ebf6ff58a5caecab40fa1406526bca4b5b9"
    control_type: "landmark"
    insightface_root: "../../../sd_model/insightface"
    pil_image_path: ???
    guidance_scale: 50
    guidance_scale_lora: 1.0
    min_step_percent: 0.02
    max_step_percent: 0.5 # annealed to 0.5 after 5000 steps [5000, 0.8, 0.11, 10000]
    use_sds: True

  freq:
    n_ref: 2
    guidance_only_steps: 0
    ref_or_guidance: "alternate"
    fit_step: 1000
    no_diff_steps: 0
    guidance_eval: 0
    n_rgb: 4

  loggers:
   wandb:
     enable: False
     project: "threestudio"
     name: "Head3D_new"

  loss:
    lambda_sd: 1.0
    lambda_lora: 0.5
    lambda_3d_sd: 0.0
    lambda_rgb: 1000.0
    lambda_mask: 100.0
    lambda_mask_binary: 0.0
    lambda_depth: 100.0
    lambda_depth_rel: 100.0
    lambda_normal: 10000.
    lambda_normal_smooth: 0.0
    lambda_3d_normal_smooth: 0.0
    lambda_normal_consistency: [1000, 500.0, 10000., 1001]
    lambda_laplacian_smoothness: [1000, 100000.0, 150000., 1001]

  optimizer:
    name: Adam
    args:
      lr: 0.005
      betas: [0.9, 0.99]
      eps: 1.e-15

trainer:
  max_steps: 6000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 6000
  enable_progress_bar: true
  precision: 32

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}